from datetime import datetime


def get_daily_template(dt: datetime) -> str:
    date_str = dt.strftime("%Y-%m-%d")
    day_name = dt.strftime("%A")
    return f"""---
date: {date_str}
day: {day_name}
tags: [daily]
---

# {date_str} — Daily Log

## 🌅 Priorities (carried from yesterday)
<!-- agent pre-fills this from previous day's uncompleted tasks -->

## 🎯 Today's Tasks

### 🖥️ Backend
- [ ] 

### 🌐 Frontend
- [ ] 

### 📊 Data Science
- [ ] 

## 🚧 Active Blockers
<!-- agent syncs from Blockers/active.md -->

## ✅ Completed Today
<!-- agent moves tasks here when you say "done" -->

## 📝 Notes / Decisions

## 🌙 EOD Summary
<!-- filled when you ask /summary -->
"""


def get_weekly_template(year: int, week: int) -> str:
    return f"""---
year: {year}
week: {week}
tags: [weekly]
---

# Week {week} Summary — {year}

## 📊 Stats at a Glance

| Domain | Tasks Done | Tasks Pending | Blockers Opened | Blockers Resolved |
|--------|-----------|---------------|-----------------|-------------------|
| Backend | 0 | 0 | 0 | 0 |
| Frontend | 0 | 0 | 0 | 0 |
| Data Science | 0 | 0 | 0 | 0 |

## 🖥️ Backend — This Week

## 🌐 Frontend — This Week

## 📊 Data Science — This Week

## 🚧 Open Blockers Entering Next Week

## 🌅 Recommended Focus for Next Week

## 🤖 AI Weekly Summary
<!-- Generated by Groq when you run /week -->
"""


def get_active_blockers_template() -> str:
    return """---
tags: [blockers, active]
---

# Active Blockers

"""


def get_context_template() -> str:
    return """---
tags: [agent-context]
---

# Agent Context

## Developer Profile
- **Focus Areas:** Backend, Frontend, Data Science
- **Vault Created:** Auto-generated by Obsidian Agent

## Active Projects
<!-- Agent will populate from your vault -->

## Technology Stack
<!-- Agent will infer from your task history -->

## Preferences
- Task format: `- [ ] Description`
- Domain tags: [BE] Backend · [FE] Frontend · [DS] Data Science

## Vault Structure
- `Daily/` — One note per day
- `Projects/` — Backend / Frontend / DataScience sub-folders
- `Weekly/` — Weekly summaries (generated on demand)
- `Blockers/` — active.md + resolved/
- `Templates/` — Note templates
- `Agent/` — This context file + changelog
"""


def get_changelog_template() -> str:
    return """---
tags: [changelog]
---

# Agent Changelog

"""


def get_project_template(name: str, domain: str) -> str:
    return f"""---
name: {name}
domain: {domain}
status: active
tags: [project, {domain.lower()}]
---

# {name}

## Overview

## Goals

## Tasks
- [ ] 

## Notes
"""
